### ISSUE TITLE
配置中心获取显示

### ISSUE THREAD

**Issue by innerpeacez** [dyc87112/spring-cloud-config-admin#100]
1.1.0  获取到配置中心显示的时候真的是这样子的么？还是我本地UI问题呢

还有

`2018-09-17 11:12:46.334  WARN 1392 --- [io-12000-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.web.client.HttpClientErrorException: 404 null`是什么原因呢

**Comment by dyc87112** [comment]
来一发截图？

**Comment by fallenangelblog** [comment]
![_20180918142413](https://user-images.githubusercontent.com/34016559/45668330-eba36f80-bb4e-11e8-8e00-34618e12c84b.png)

**Comment by innerpeacez** [comment]
上面的图片

**Comment by dyc87112** [comment]
@stone-jin 每个表格的标题样式还要调一下

**Comment by stone-jin** [comment]
好的，我改下~不过这个标题，感觉也太长了。

**Comment by stone-jin** [comment]
![image](https://user-images.githubusercontent.com/6525544/46914885-31c8e300-cfd6-11e8-8c8c-ebdd28e5e074.png)
调整了样式，并且模态框调整变大，如上图效果。
