### ISSUE TITLE
1.1.0-RELEASE 通过yaml导入需要二次保存才能生效

### ISSUE THREAD

**Issue by fasoal** [dyc87112/spring-cloud-config-admin#103]
![image](https://user-images.githubusercontent.com/14243815/45667308-39b67400-bb4b-11e8-824a-e084047dc29f.png)
点击这个保存不是每次都会生效

**Comment by dyc87112** [comment]
这个应该是描述上的问题，目前YAML和Properties主要是编辑使用，最后会反应到列表里，真正提交是在列表页中的“保存”

**Comment by dyc87112** [comment]
@stone-jin 看看是不是在1.1.1中修改一下这个按钮的描述把，比如叫：确认？

**Comment by stone-jin** [comment]
已修改~
