### ISSUE TITLE
http://user:password@localhost:8761/eureka/,这种形式的eureka，会报401错误

### ISSUE THREAD

**Issue by innerpeacez** [dyc87112/spring-cloud-config-admin#109]
Basic之后的Eureka，通过UrlMaker4Eureka解析报org.springframework.web.client.HttpClientErrorException: 401 null。

我这边的两种解决办法

![image](https://user-images.githubusercontent.com/37059529/45791413-2840a980-bcbc-11e8-9ef0-619e0af6e9df.png)

1.
`    private String getConfigInfoHeader(String url) {
        if (url.contains("@")) {
            String authStr = url.substring(url.indexOf("//") + 2, url.indexOf("@"));
            String[] auth = authStr.split(":");
            String auth_Str = auth[0] + ":" + auth[1];
            byte[] encodedAuth = Base64.encodeBase64(auth_Str.getBytes(Charset.forName("US-ASCII")));
            String authHeader = "Basic " + new String(encodedAuth);
            HttpHeaders headers = new HttpHeaders();
            headers.set("authorization", authHeader);
            return restTemplate.exchange(url, HttpMethod.GET, new HttpEntity<>(null, headers), String.class).getBody();
        } else {
            return restTemplate.getForObject(url, String.class);
        }
    }`

2.
`   private String getConfigInfo(String url) {
        if (url != null && url.contains("@")) {
            RestTemplate restTemplate = new RestTemplate();
            String authStr = url.substring(url.indexOf("//") + 2, url.indexOf("@"));
            String[] auth = authStr.split(":");
            restTemplate.getInterceptors().add(new BasicAuthorizationInterceptor(auth[0], auth[1]));
            return restTemplate.getForObject(url, String.class);
        }
        // 访问eureka接口获取一个可以访问的实例
        return this.restTemplate.getForObject(url, String.class);
    }`

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/45791466-60e08300-bcbc-11e8-8cca-c2d1c6b96a52.png)

**Comment by innerpeacez** [comment]
![image](https://user-images.githubusercontent.com/37059529/45791478-6b9b1800-bcbc-11e8-8125-662cf52bf1e4.png)

**Comment by dyc87112** [comment]
@innerpeacez 感谢建议，可以提交一个PR吗？

**Comment by Fijileijun** [comment]
我已经提交了PR了@dyc87112
