### ISSUE TITLE
All-in-one模式，使用git存储，需要配置db，请问使用mysql的schema文件在哪里可以看到呢

### ISSUE THREAD

**Issue by liangweilu** [dyc87112/spring-cloud-config-admin#112]
我采用All-in-one模式，使用git存储，运行server的时候提示我需要配置DB，但是没有看到哪里有数据库的schema文件，我使用的DB是mysql。请问在哪里能看到schema文件

**Comment by liangweilu** [comment]
我按照`com.didispace.scca.rest.domain`包中的对象创建了`user`表和`user_log`表，目前可以运行。请问能否提供一下需要用到的sql文件呢

**Comment by dyc87112** [comment]
配置个参数试试：spring.jpa.properties.hibernate.hbm2ddl.auto=update
