### ISSUE TITLE
spring-cloud-config配置主要痛点

### ISSUE THREAD

**Issue by chenkline** [dyc87112/spring-cloud-config-admin#114]
您好，你这个项目很好，但是我觉得目前开发的主要功能没有戳中主要痛点
我们在生产使用spring-cloud-config的感觉，最大3个痛点
1. 动态刷新触发界面缺失，
2. 不支持灰度配置，比如根据应用节点标识(如:ip)灰度发布配置，这些配置仅在指定节点生效，即使其它节点重启也不会应用到这些灰度配置
3.依赖gitlab，gitlab太不轻量，gitlab操作对测试和运维操作人员不够友好，配置中心的git配置对应运维不够友好， 如果改为使用DB存储，又缺失DB的配置操作界面

**Comment by dyc87112** [comment]
您说的几项功能，我们都有计划要完善。对于第三个问题，我们不排斥用任何存储，所以对db、git等都会以插件的方式加以支持
