### ISSUE TITLE
前端登陆后有个js加载失败

### ISSUE THREAD

**Issue by shinji3887** [dyc87112/spring-cloud-config-admin#132]
控制台报错：
指向“http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js”的 <script> 加载失败。
目前来看这个js好像不影响使用，不知道具体是干嘛的
是否能改成本地加载？

**Comment by dyc87112** [comment]
我试了一下这个url是可以访问到的，您再看看是否是网络问题导致

**Comment by shinji3887** [comment]
可能我没有描述清楚，我们应用是部署在内网的，无法访问公网
这个js是需要连到公网加载的，能否改成本地local的js？

**Comment by stone-jin** [comment]
@shinji3887 ，那我到时打包到工程里面吧

**Comment by shinji3887** [comment]
> @shinji3887 ，那我到时打包到工程里面吧

谢谢
