### ISSUE TITLE
demo用户名/密码不对

### ISSUE THREAD

**Issue by lunbobi** [dyc87112/spring-cloud-config-admin#143]
mysql模式启动后，登录界面输入：admin/123456 .提示认证失败,默认密码是多少？

**Comment by AnoyiX** [comment]
账号密码，在第一次启动时会有日志输出，默认 admin/spring4all   详见 [InitAdminAccountRunner.java](https://github.com/dyc87112/spring-cloud-config-admin/blob/1.2.x/scca-rest/src/main/java/com/didispace/scca/rest/runner/InitAdminAccountRunner.java)
