### ISSUE TITLE
[配置管理]界面中“配置中心获取”的意义？

### ISSUE THREAD

**Issue by alliswellhuan** [dyc87112/spring-cloud-config-admin#41]
[配置管理]界面中“配置中心获取”的链接点击进去之后会查询出当前项目对应版本的配置信息，既然存在“当前存储配置详情”，那“配置中心获取”链接的意义是什么呢？是因为“当前存储配置详情”会被编辑，而只读的“配置中心获取”功能可以参考对比吗？@stone-jin

**Comment by stone-jin** [comment]
@dyc87112

**Comment by dyc87112** [comment]
主要用来对比参考真正从配置中心拿到的是什么内容，这里有很多因素会影响，比如：config-server的override等，如果发现应用加载有问题，可以用这个功能查查看

**Comment by alliswellhuan** [comment]
恕我愚钝，“主要用来对比参考真正从配置中心拿到的是什么内容“——这个真正从配置中心拿到的内容是要从哪里看？初衷是要从【配置中心获取的配置】连接点击进入查看吗

对于这里的设计依旧感到困惑，我尝试过在config-server设置override：
spring.cloud.config.server.overrides.myaddress=shanghai
同时在配置管理中添加对应的key和value，其中key为myaddress  value为hangzhou
然后创建config-client访问myaddress属性，获取的值为shanghai  符合overrides属性

查看【配置中心获取的配置】中myaddress依旧为hangzhou

且配置管理中【保存配置】和【配置中心获取的配置】值都是来源于property数据表，两者数据来源皆相同

**Comment by stone-jin** [comment]
@dyc87112

**Comment by dyc87112** [comment]
@alliswellhuan 前端没有展示全导致

**Comment by dyc87112** [comment]
@stone-jin 接口返回内容如下

![image](https://user-images.githubusercontent.com/3391170/43304636-75636d78-91a7-11e8-859a-ec5fe1802800.png)

展现的时候分多个表格，表哥加格标题，用name的值。
