### ISSUE TITLE
服务维度配置管理 页面中 `配置中心获取`链接点击的时候发起了两个请求

### ISSUE THREAD

**Issue by dyc87112** [dyc87112/spring-cloud-config-admin#44]
![image](https://user-images.githubusercontent.com/3391170/43304850-2fb7f388-91a8-11e8-872c-5103a5bb9e6b.png)

**Comment by stone-jin** [comment]
这个看了下 逻辑里面我只调用了一次，可能是因为angular导致某一块需要重新渲染，然后重新请求了下对应区域的数据。
逻辑没问题。
所以close掉了
