### ISSUE TITLE
配置管理页面中的yml模式和property模式的编辑区高度问题

### ISSUE THREAD

**Issue by dyc87112** [dyc87112/spring-cloud-config-admin#46]
![image](https://user-images.githubusercontent.com/3391170/43305803-98f9c012-91ab-11e8-8f9c-4203defbc375.png)

目前的高度有点低，配置多多额时候查看不太方便，看看是否可以让高度跟底部更贴合一些，增高这块空间的利用率

**Comment by stone-jin** [comment]
已经在1.1分支上修改了
