### ISSUE TITLE
用户管理：创建用户、修改用户、删除用户、重置密码

### ISSUE THREAD

**Issue by dyc87112** [dyc87112/spring-cloud-config-admin#49]
【后端部分】

1. User实体：账户、密码（md5加密）、昵称
2. User实体的增删改查接口、重置密码接口
3. 默认提供管理员账户：admin/spring4all

【前端部分】

1. “用户管理”功能菜单的实现，表格形式显示所有User实体，可以新增、删除、修改、重置密码

**Comment by pandalin** [comment]
是否可以整合自有LDAP?

**Comment by stone-jin** [comment]
开发完毕，已经在分支1.1.0-anoyi分支上， @dyc87112 超哥到时看下功能对不对
