### ISSUE TITLE
用户登录与登录检查

### ISSUE THREAD

**Issue by dyc87112** [dyc87112/spring-cloud-config-admin#50]
【后端部分】

1. 提供登录接口、登出接口
2. 各功能性接口的登录检查（未登录的返回登录页面

【前端部分】

1. 登录页对接登录接口
2. 功能页面右上显示用户信息和登出操作

**Comment by stone-jin** [comment]
登录，登出，还有显示用户信息 ok了。

然后在分支1.1.0-anoyi上开发。

@dyc87112 需要验证下功能。

**Comment by stone-jin** [comment]
测试了几种情况，登录登出都可以用了，同时登录进来后，右上角可以查看用户信息
