### ISSUE TITLE
没有主清单属性

### ISSUE THREAD

**Issue by zhangcl2002** [dyc87112/spring-cloud-config-admin#55]
[INFO] spring-cloud-config-admin .......................... SUCCESS [  0.327 s]
[INFO] scca-core .......................................... SUCCESS [  7.129 s]
[INFO] scca-discovery-consul .............................. SUCCESS [  1.206 s]
[INFO] scca-discovery-eureka .............................. SUCCESS [  1.075 s]
[INFO] scca-persistence-git ............................... SUCCESS [  1.013 s]
[INFO] scca-persistence-db ................................ SUCCESS [  0.925 s]
[INFO] scca-rest .......................................... SUCCESS [  2.421 s]
[INFO] scca-ui ............................................ SUCCESS [  5.596 s]
[INFO] scca-config-server-db .............................. SUCCESS [  0.523 s]
[INFO] scca-config-server-git ............................. SUCCESS [  0.294 s]
[INFO] scca-rest-server-access-config-server-db ........... SUCCESS [  0.984 s]
[INFO] scca-rest-server-access-config-server-git .......... SUCCESS [  0.625 s]
[INFO] scca-rest-server-with-config-server-db ............. SUCCESS [  0.755 s]
[INFO] scca-rest-server-with-config-server-git ............ SUCCESS [  0.763 s]
[INFO] scca-ui-server ..................................... SUCCESS [  0.512 s]
[INFO] scca-ui-server-with-rest-server .................... SUCCESS [  0.623 s]
[INFO] scca-ui-server-with-all ............................ SUCCESS [  0.912 s]
[INFO] scca-test-client ................................... SUCCESS [  0.623 s]
[INFO] ------------------------------------------------------------------------

打包都完成了，但java -jar 无法启动，说jar中没有主清单属性
d:\spring-cloud-config-admin-1.1.x\scca-use-cases\scca-ui-server-with-all\target>java -jar scca-ui-server-with-all-1.0.0
-SNAPSHOT.jar
scca-ui-server-with-all-1.0.0-SNAPSHOT.jar中没有主清单属性

d:\spring-cloud-config-admin-1.1.x\scca-use-cases\scca-ui-server-with-all\target>

**Comment by stone-jin** [comment]
@dyc87112

**Comment by dyc87112** [comment]
1.1.0优化该问题

**Comment by dyc87112** [comment]
同 #75
