### ISSUE TITLE
Git配置中心仓库已有yml配置，通过管理端获取的配合解析的不正确

### ISSUE THREAD

**Issue by david1228** [dyc87112/spring-cloud-config-admin#59]
项目中已使用了Git作为配置中心，当启动SCCA后配置好项目和环境变量，从配置中心获取yml配置时解析的不对，目前是只支持properties方式吗？

将yml配置直接拷贝到SCCA界面上，保存之后，Git仓库的配置yml格式的变成了properties形式的文件了。

**Comment by dyc87112** [comment]
目前Git存储的时候只支持Properties的读写，Yaml的支持还需要扩展，我列入后续的版本计划中，感谢提出宝贵意见～

**Comment by dyc87112** [comment]
1.1.0将同时支持properties文件和yaml文件存储
