### ISSUE TITLE
当配置中心启用了用户名密码认证，此时访问Dashboard和配置中心获取数据时报错「401 authorization required 」

### ISSUE THREAD

**Issue by david1228** [dyc87112/spring-cloud-config-admin#61]
当配置中心启用了用户名密码认证，此时Dashbord和配置中心获取数据时报错「401 authorization required 」
代码里是通过okhttpclient实现的，可要求配置时形如http://user:pass@config.com？，解析出user和pass。
如下方式：
Request  request = new Request.Builder()
                    .header("Authorization", Credentials.basic(“user”,“pass”))
                    .url(url)
                    .get()
                    .build();

**Comment by stone-jin** [comment]
@dyc87112

**Comment by dyc87112** [comment]
1.1.0解决该问题

**Comment by dyc87112** [comment]
1.1.0版本之后添加如下配置来解决该问题

```
scca.config-server.username=admin
scca.config-server.password=123456
```
