### ISSUE TITLE
加密key设置比较长时，在配置管理中右侧的显示的界面key显示不全。

### ISSUE THREAD

**Issue by david1228** [dyc87112/spring-cloud-config-admin#64]
加密key设置比较长时，在配置管理中右侧的显示的界面key显示不全。
![image](https://user-images.githubusercontent.com/2298080/43834993-c9e0321a-9b42-11e8-941c-fb3e6f0aa6e6.png)

**Comment by stone-jin** [comment]
@david1228 感谢反馈，请问你显示器配置是多少？

**Comment by shikonglaike** [comment]
确实有这个问题。因为有的时候key会很长的。weweddd.cms.account.a9325e9077d34e64a5c92a45bf12312312b.secertKey

**Comment by stone-jin** [comment]
这么长呀。你能F12或者打开开发者工具，全屏，然后再Console里面输入：window.innerWidth，看一下数字是多少。

我需要通过响应式布局帮你解决这个问题。
如下图：
![image](https://user-images.githubusercontent.com/6525544/43874469-a186f2aa-9bbe-11e8-9538-beb5f098d98c.png)

**Comment by stone-jin** [comment]
@shikonglaike @david1228

**Comment by stone-jin** [comment]
嗯嗯，跟用户沟通后，解决办法：右侧的由于会很长，所以准备改法就是出横向滚动条。

**Comment by david1228** [comment]
@stone-jin 我的是macpro 15.6，显示器分辨率是默认的，显示器配置是指啥哈？
