### ISSUE TITLE
项目删除出错

### ISSUE THREAD

**Issue by ChinaSilence** [dyc87112/spring-cloud-config-admin#69]
分支：1.1.0-anoyi

模式: all-in-one  db

环境配置  
配置中心绝对地址   http://localhost:8080/xhr

报错信息

JSON parse error: Can not deserialize instance of java.lang.Integer out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.Integer out of START_OBJECT token at [Source: java.io.PushbackInputStream@1a4789a7; line: 1, column: 1]

**Comment by haodanhui521** [comment]
请问这个解决了吗？方便告诉我怎么解决吗
