### ISSUE TITLE
【配置管理】中“一键加密”的效果

### ISSUE THREAD

**Issue by alliswellhuan** [dyc87112/spring-cloud-config-admin#72]
在【加密管理】中配置了两条数据 key1  key2 ；在【配置管理】的加密key清单中可以看到key1 key2，然后点击“一键加密”的按钮操作，可以看到左侧配置列表中有刷新一样的效果，但是并没有看到任何实质性的数据变化，对该功能表示困惑，是该功能尚未实现还是我理解有误？

**Comment by dyc87112** [comment]
浏览器的console中有报错信息吗？

**Comment by alliswellhuan** [comment]
F12调试过了，当点击【一键加密】的按钮操作后 console里面没有任何报错信息

**Comment by alliswellhuan** [comment]
不好意思，是我理解有问题，将key输入了一个不存在的，实际运行ok
