### ISSUE TITLE
all-in-one-db 模式使用idea的maven插件打包，没有依赖的jar包

### ISSUE THREAD

**Issue by kofwangshuai** [dyc87112/spring-cloud-config-admin#75]
spring-cloud-config-admin/scca-use-case/scca-ui-server-with-all 项目使用idea的maven插件打包以后的jar包只有4k的大小，缺失依赖的jar包 。（备注 ：使用idea是可以正常启动项目的。）

同时也会发现 scca-core ，scca-discovery-**，scca-perisitence-** 等等项目都是的jar包文件的大小都是很小。

**Comment by dyc87112** [comment]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.14.RELEASE</version>
    </parent>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

1.1.0的例子更新了，主要是pom.xml中的这两个内容
