### ISSUE TITLE
配置页面，加密按钮调用接口，返回失败

### ISSUE THREAD

**Issue by stone-jin** [dyc87112/spring-cloud-config-admin#9]
调用接口/xhr/property/encrypt?envId=1&value=111
然后返回：
{"code":200,"data":"{\"timestamp\":1530630775718,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"java.lang.IllegalArgumentException\",\"message\":\"Unable to initialize due to invalid secret key\",\"path\":\"//scca-config-server/encrypt\"}","message":null,"timestamp":1530630775719}

**Comment by stone-jin** [comment]
@dyc87112

**Comment by dyc87112** [comment]
需要安装JCE，再尝试一下，后续这一步我补充到文档

**Comment by stone-jin** [comment]
我这边已经能加密了，可能跟上次替换的JCE有关，但是上次替换后没有直接生效，好像重启电脑后生效的。
我环境是mac
