### ISSUE TITLE
从配置中心获取配置的数据太长会超出页面

### ISSUE THREAD

**Issue by yingw** [dyc87112/spring-cloud-config-admin#96]
“配置管理” - “配置中心获取”，如果值过长，会超出页面看不到，且页面各种分块异常。

**Comment by stone-jin** [comment]
![image](https://user-images.githubusercontent.com/6525544/46914891-60df5480-cfd6-11e8-9c01-483542a5dc4d.png)

@yingw ，改成了这样的效果~
